### ISSUE TITLE
Shen

### ISSUE THREAD

**Issue by sshen2020** [vi3k6i5/GuidedLDA#47]
Hello,

I was trying to install the package after failing to install using pip and received the following error. I'm on Mac OS and using python 3.7.

Thanks!

$ sh build_dist.sh
find guidedlda -name "*.pyx" -exec cython {} \;
Ok to continue (y/n)? y
Building distribution
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/Users/a658265/.conda/envs/md_email4/lib/python3.7/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Users/a658265/.conda/envs/md_email4/lib/python3.7/site-packages/pbr/util.py", line 271, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/Users/a658265/.conda/envs/md_email4/lib/python3.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/Users/a658265/.conda/envs/md_email4/lib/python3.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/Users/a658265/.conda/envs/md_email4/lib/python3.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/Users/a658265/.conda/envs/md_email4/lib/python3.7/site-packages/pbr/packaging.py", line 876, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name guidedlda was given, but was not able to be found.
error in setup command: Error parsing /Users/a658265/Documents/Argus/Service Model Opt/GuidedLDA-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name guidedlda was given, but was not able to be found.

**Comment by bohyunshin** [comment]
Another Mac OS and python 3.7 user, but I got different error.
However, I solved the installation issue by making virtual env and install python 3.6 on that virtual env. It may be problems that c compiler in python raises error on version 3.7. So, suggest to install GuidedLDA library in python 3.6
Just left a comment to help you in case.

**Comment by carlosparadis** [comment]
> Another Mac OS and python 3.7 user, but I got different error. However, I solved the installation issue by making virtual env and install python 3.6 on that virtual env. It may be problems that c compiler in python raises error on version 3.7. So, suggest to install GuidedLDA library in python 3.6 Just left a comment to help you in case.

Thank you so much for this; this was finally what made GuidedLDA work through pip for me too. Nothing else did.
