### ISSUE TITLE
Unable to install Guidedlda package on windows 11 jupyter notebook kindly help need in urgent basis...Thanku in advance

### ISSUE THREAD

**Issue by Richa-Kushwaha** [vi3k6i5/GuidedLDA#67]
Collecting guidedlda
  Using cached https://files.pythonhosted.org/packages/f8/ee/6d6e2b3525388399e12a4482554c7529a5fcf5e99c50a60abaa02894b8bf/guidedlda-2.0.0.dev22.tar.gz
Note: you may need to restart the kernel to use updated packages.
    ERROR: Command errored out with exit status 1:
     command: 'D:\ana\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RICHAK~1\\AppData\\Local\\Temp\\pip-install-s47fldyn\\guidedlda\\setup.py'"'"'; __file__='"'"'C:\\Users\\RICHAK~1\\AppData\\Local\\Temp\\pip-install-s47fldyn\\guidedlda\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\RICHAK~1\AppData\Local\Temp\pip-install-s47fldyn\guidedlda\pip-egg-info'
         cwd: C:\Users\RICHAK~1\AppData\Local\Temp\pip-install-s47fldyn\guidedlda\
    Complete output (37 lines):
    D:\ana\lib\site-packages\setuptools\dist.py:773: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      % (opt, underscore_opt)
    D:\ana\lib\site-packages\setuptools\dist.py:773: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
      % (opt, underscore_opt)
    D:\ana\lib\site-packages\setuptools\dist.py:773: UserWarning: Usage of dash-separated 'pre-hook.sdist_pre_hook' will not be supported in future versions. Please use the underscore name 'pre_hook.sdist_pre_hook' instead
      % (opt, underscore_opt)
    D:\ana\lib\site-packages\setuptools\dist.py:57: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    D:\ana\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    D:\ana\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    D:\ana\lib\site-packages\setuptools\dist.py:773: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      % (opt, underscore_opt)
    D:\ana\lib\site-packages\setuptools\dist.py:773: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
      % (opt, underscore_opt)
    D:\ana\lib\site-packages\setuptools\dist.py:773: UserWarning: Usage of dash-separated 'pre-hook.sdist_pre_hook' will not be supported in future versions. Please use the underscore name 'pre_hook.sdist_pre_hook' instead
      % (opt, underscore_opt)
    Error parsing
    Traceback (most recent call last):
      File "D:\ana\lib\site-packages\pbr\core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "D:\ana\lib\site-packages\pbr\util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "D:\ana\lib\site-packages\pbr\util.py", line 579, in wrap_commands
        for cmd, _ in dist.get_command_list():
      File "D:\ana\lib\site-packages\setuptools\dist.py", line 968, in get_command_list
        cmdclass = ep.load()
      File "D:\ana\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 194, in load
        module = import_module(match.group('module'))
      File "D:\ana\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'setuptools.command.bdist_wininst'
    error in setup command: Error parsing C:\Users\RICHAK~1\AppData\Local\Temp\pip-install-s47fldyn\guidedlda\setup.cfg: ModuleNotFoundError: No module named 'setuptools.command.bdist_wininst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
​

**Comment by Richa-Kushwaha** [comment]
when used "conda install guidedlda" in anaconda in the administrator mode:
ERROR:
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - guidedlda

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
